
```{r}

 packages = c('quantmod')

# Install all Packages with Dependencies
install.packages(packages, dependencies = TRUE)

# Load all Packages
lapply(packages, require, character.only = TRUE)

```


 
```{r}
# Required Packages
packages = c('tseries', 'forecast')

# Install all Packages with Dependencies
install.packages(packages, dependencies = TRUE)

# Load all Packages
lapply(packages, require, character.only = TRUE)

```
```{r}
# Required Packages
packages = c('FinTS', 'rugarch')

# Install all Packages with Dependencies
install.packages(packages, dependencies = TRUE)

# Load all Packages
lapply(packages, require, character.only = TRUE)



```


```{r}

# Create an environment to store the data
stock_data <- new.env()

# Define the stock symbol
stock_symbol <- 'ADANIENT.BO'  # ADANIENT.BO is the ticker symbol for Adani Enterprises Ltd on BSE

# Define the start and end dates
start_date <- as.Date('2019-01-01')
end_date <- as.Date('2023-12-31')

# Fetch the stock data
getSymbols(Symbols = stock_symbol, src = 'yahoo', from = start_date, to = end_date, env = stock_data)
```


```{r}

# Extract closing prices
adani_prices <- Cl(stock_data[[stock_symbol]])

# Remove missing values
adani_prices <- na.omit(adani_prices)

# View the resulting closing prices
head(adani_prices)
 
```


```{r}

# Check the class of the stock_price object
class(adani_prices)
```


```{r}

# Augmented Dickey-Fuller (ADF) Test for Stationarity with Adani Enterprises Ltd on BSE Data
# *******************************************************************

# Perform Augmented Dickey-Fuller (ADF) Test
adf_result <- adf.test(adani_prices)

# Print the ADF test result
print(adf_result)

#In this case, since the p-value (0.4087) is greater than a typical significance
#level like 0.05, we fail to reject the null hypothesis.
#Therefore, we do not have enough evidence to conclude that the time series is stationary.
```


```{r}
adani_ds = diff(adani_prices);  
adani_ds
  # Adani Enterprises Ltd  (First)return Difference Time-Series
```
  

```{r}
adani_ds=na.omit(adani_ds)
 
adf_test_adani_ds = adf.test(adani_ds); adf_test_adani_ds
```


```{r}
# Ljung-Box Test for Autocorrelation -  Data
# ***********************************************

lb_test_adani_ds = Box.test(adani_ds)# Inference : adani Difference (Stationary)
 lb_test_adani_ds
#In this case, since the p-value (4.294e-05) is much smaller than a typical significance level like 0.05,
#we reject the null hypothesis. Therefore, we have evidence to suggest that there is significant autocorrelation in the time series. | NULL: No Auto correlation | Alternate: Auto Correlation
```


```{r}

#Autocorrelation Function (ACF) | Partial Autocorrelation Function (PACF)
# *****************************************************************************

acf(adani_prices) # ACF of adani Series
```


```{r}

pacf(adani_prices) # PACF of adani Series
```


```{r}


acf(adani_ds) # ACF of adani Series
```


```{r}
pacf(adani_ds) # PACF of adani Difference (Stationary) Series
```


```{r}

arma_pq_adani_ds = auto.arima(adani_ds); arma_pq_adani_ds
```


```{r}
adani_ds_fpq = forecast(arma_pq_adani_ds, h = 500)
plot(adani_ds_fpq)
```


```{r}
lb_test_arma_pq_adani_ds = Box.test(arma_pq_adani_ds$residuals); lb_test_arma_pq_adani_ds
```


```{r}
# Test for Volatility Clustering or Heteroskedasticity: Box Test
adani_ret_sq = arma_pq_adani_ds$residuals^2 # Residual Variance (Since Mean Returns is approx. 0)
plot(adani_ret_sq)
```


```{r}
adani_ret_sq_box_test = Box.test(adani_ret_sq,lag = 1 ) # H0: Return Variance Series is Not Serially Correlated
adani_ret_sq_box_test # Inference : Return Variance Series is Autocorrelated (Has Volatility Clustering)
```


```{r}
# Test for Volatility Clustering or Heteroskedasticity: ARCH Test
adani_ret_arch_test = ArchTest(arma_pq_adani_ds$residuals^2,lag = 1) # H0: No ARCH Effects
adani_ret_arch_test # Inference : Return Series is Heteroskedastic (Has Volatility Clustering)
```
 
 


```{r}
# GARCH Model
garch_model1 = ugarchspec(variance.model = list(model = 'sGARCH', garchOrder = c(1,1)), mean.model = list(armaOrder = c(1,1), include.mean = TRUE))
adani_ret_garch1 = ugarchfit(garch_model1, data = arma_pq_adani_ds$residuals^2); adani_ret_garch1
```


```{r}
# GARCH Forecast
adani_ret_garch_forecast1 = ugarchforecast(adani_ret_garch1, n.ahead = 500); adani_ret_garch_forecast1
```


```{r}
plot(adani_ret_garch_forecast1, which = 1)
```


```{r}
# Plot the specified aspect of the GARCH forecast
plot(adani_ret_garch_forecast1, which = 3)

```


 